### PR TITLE
Currying functions for performance gain

### PR DESCRIPTION
**Pull request by luntan-maker**
I went through all the files in `src/*`, and curried functions that were repeatedly used within a while or for loop outside of an if statement. I've tried to have some form of literate programming by maintaining the naming convention and appending `_partial`. I did not add comments, since it seemed somewhat straightforward what was going on. I would be more than happy to add comments if you will tell me what you would like me to explain. This should address #148 .

### CODE REVIEW

**Comment by rafaqz** [comment]
Ok, so I feel there may have been some misunderstanding somewhere!

The idea was to add these methods everywhere for users to call themselves:
```julia
GO.intersects(x) = Base.Fix1(GO.intersects, x)
```

As anshul demonstrated. This gives us a "curried" `Fix1` objects to use in `map` and similar functions for the convenience and nice syntax. So we could do `map(intersects(mygeom), othergeoms)` to get a vector of Bool, rather than always having to do `map(g -> intersects(g, mygeom), othergeoms)`. Does that make sense?

Currying anonymous functions explicitly like you have here can sometimes give a performance gain where it can help the compiler (for pretty arcane reasons), but I'm not sure it will be measureable in this case.

**Comment by luntan-maker** [comment]
I think I understand what you are saying. 
Just to be sure though. You want to use `Base.Fix1` and `Base.Fix2` to clean up and make the code more readable/semantic.
This leaves us with two options; build on top of what I already have, or remove it. Which would you prefer?

**Comment by rafaqz** [comment]
Hmm... not really! 

Essentially I'm talking about a different PR to what you have! It would just define methods like this:

```juila
GO.intersects(x) = Base.Fix1(GO.intersects, x)
GO.disjoint(x) = Base.Fix1(GO.disjoint, x)
# etc etc
```

For all of the predicates in the `geom_relations` folder. It would also add tests for all of these in the related test files.

**Comment by luntan-maker** [comment]
I didn’t get what you are saying from what they were saying. Also, I completely missed the part where you said draft PR. So, with your okay, I plan to do the following

1. 	Close this PR
2. 	Clone again or revert current repository
3. 	Open a draft PR
4. 	Start working on what I believe you want

Sound good?

**Comment by rafaqz** [comment]
First maybe write out in your own words what you think we want! Just to be sure there is no communication issue this time

**Comment by luntan-maker** [comment]
Interesting. Thank you for that response. That gives me clarity. I feel this issue is not a good fit for me. You'll need to get someone else to work on this for you. Thank you for the opportunity. Best of luck to you.

**Comment by rafaqz** [comment]
No worries

**Pull request closed without merging**
